### ISSUE TITLE
Q061: incorrect field reference

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1076]
Q061 is coded to check the proportion of HOEPA status but should instead be checking property type.

**Comment by keileyo** [comment]
@Kibrael is this referencing Q061 like the title or Q059 like the comment? I think this is in reference to Q061 since that is a macro quality edit, and you reference proportion of loans. If it is Q061 then :+1: it should be checking the proportion of loans by property type, lien status, action taken type and rate spread.

**Comment by Kibrael** [comment]
@keileyo Thanks for the catch, changed to Q061.
