### ISSUE TITLE
Q053: edit doesn't fail, hangs on validation

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1078]
This edit did not return a failure result for the test file. The file was sent to a local instance of the back-end interactive API mode. Original issue #226.

The file was tested in python with the following results: 434 rows failed the edit criteria (numerator) and 486 rows were originations (denominator) resulting in an 89% fail rate for the file. This should trigger the edit as the threshold is <=1%.

I am unable to validate Cassandra and Zookeeper and the other pieces as I don't know how to do that. If you believe this result is in error, let me know and I will close the issue.

**Comment by keileyo** [comment]
:+1:

**Comment by jmarin** [comment]
These tickets are not very useful. Here are the reasons:
- We don't know what _python results_ means. The reference implementation for the HMDA edits is this repository. 
- We need to be able to consistently reproduce the bug. In order to do that, a developer requires exact steps taken to reproduce it. This may include sample data, which is missing here (did we use a file in this repo? If so, which one?)
- Repeating the filter conditions is redundant, they are clearly specified both in the code implementation [here](https://github.com/cfpb/hmda-platform/blob/master/validation/src/main/scala/hmda/validation/rules/lar/macro/Q053.scala#L23) and in the original GitHub issue [here](https://github.com/cfpb/hmda-platform/issues/226)

A quick look at the code doesn't reveal obvious errors, it seems to be correctly implemented. There could be runtime errors or other issues when running this edit as part of the validation step, but in order to verify that we need to have a consistent and reproducible test that demonstrates that there is a bug. 

We also need details about how the test was done. Was it done in an instance of HMDA Platform running locally in development mode? Was it tested with the deployed instance in the development cluster? If the latter, were all dependencies (`Cassandra`, `Zookeeper`, etc.) verified in order to rule out other issues and guarantee that we wouldn't see false positives?
