### ISSUE TITLE
Email the user when we've received their signature

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#1126]
The user's email is available in the JWT.

Sample content:
Email subject: __HMDA Filing Successful__
Email body:
Congratulations, you've completed filing your HMDA data for filing period `<filing period>`.
We received your filing on `<time stamp>`.
Your receipt is `<hash>`.

**Comment by schbetsy** [comment]
Do we just want to send the confirmation to the user who did the signature? I'm wondering if the other users for that institution should receive any sort of confirmation too.

**Comment by awolfe76** [comment]
I would think it would be good to email all users for that institution. Would certainly help with knowing a submission is completed ... without having to access the app.

**Comment by nickgrippin** [comment]
What should be the language in the email?

**Subject**: HMDA Filing Submission Receipt
**Body**: 
You've successfully completed your HMDA Filing.  
Receipt #abc123
Timestamp: 20170101

**Comment by wpears** [comment]
We might also want some language about contacting HMDA help, maybe something about "no further action is needed", etc.
@keileyo @designlanguage

**Comment by keileyo** [comment]
Overwhelming feedback at the vendor meeting today that we should send the email to all users from the institution.

**Comment by nickgrippin** [comment]
So, we've hit a significant design problem.  The backend has no idea who the users are for an institution.  The best thing we have is list of all the email domains (e.g. "bank0.com"), but we're not even aware of what user is currently logged in.  We'll have to interface with Keycloak somehow in order to get the list of emails linked to the institution ID ( @hkeeler ).  

The other problem is that we have to add a new library dependency in order to send email from the platform (currently, the best choice is Java Mail).

**Comment by keileyo** [comment]
@nickgrippin thanks for the update - can you bring it up at standup? 

As far as the actual message goes, I suggest:

Subject: HMDA Filing Submission Receipt
Body:
Congratulations, you've successfully completed your HMDA Filing for `<filing period>`. No further action is needed. 
Receipt #abc123
Timestamp: 20170101

I would not suggest including HMDA Help in this specific email. All of our other Keycloak generated emails include links to HMDA Help, but in the case of a successful filing, I am afraid that it would just lead to people emailing to be DOUBLE sure that we got the file, which would diminish the whole purpose of the email.

**Comment by schbetsy** [comment]
Since Keycloak already has the information necessary (which users have created accounts for this institution), and the ability to send email, it seems like we should send the email from there, not from Platform. Is it possible to send custom email from Keycloak (in addition to the 2FA and other auth-related emails we already send)?

**Comment by schbetsy** [comment]
@keileyo Should we include the institution name in the email text? Users who represent multiple institutions might be confused if the email doesn't specify which one it's for.

**Comment by hkeeler** [comment]
The SQL query for retrieving all users for a given institution from the Keycloak db looks something like (_Bank 0_ in this example).  :

```sql
SELECT ue.first_name, ue.last_name, ue.email
FROM user_entity AS ue
INNER JOIN user_attribute AS ua ON ua.user_id = ue.id
WHERE ue.realm_id = 'hmda'
AND ue.enabled = 't'
AND ue.email_verified = 't'
AND ua.name = 'institutions'
AND ua.value = '6999998';
```

```
 first_name | last_name |       email
------------+-----------+--------------------
 Jane       | Doe       | jane.doe@bank0.com
 Jim        | Doe       | jim.doe@bank0.com
 John       | Doe       | john.doe@bank0.com
```
This includes the users' first/last names in case you want to include that in the email.

Also, for debugging, here's the easiest way to access the database directly:

```
docker-compose exec keycloak_db psql -h keycloak_db -U keycloak keycloak
```

**Comment by hkeeler** [comment]
Actually, there is a bit of a wrinkle here.  The `institutions` attribute is a comma-separated list when a given user is associated with more than one user.  And I don't think it is completely safe to just switch...

```sql
AND ua.value = '6999998'
```

...to...

```sql
AND ua.value LIKE '%6999998%'
```

...because for low-numbered RSSDs, say '99' would pick up all sorts of _other_ records.  We may need to think about this a bit more.  You may have to do some post-processing of records, filtering out any records that aren't _really_ associated with the institution in question.

**Comment by nickgrippin** [comment]
Would it work if we added three statements to the value check?  Something like this:
```sql
AND (ua.value = '6999998'
  OR ua.value LIKE '6999998,%'
  OR ua.avlue LIKE '%,6999998' 
  OR ua.value LIKE '%,6999998,%')
```

**Comment by hkeeler** [comment]
Huh.  Yeah. That might...just...work.  Performance is likely not-great as you may be doing as many as 3 table scans with all those `LIKE`s, but it is not going to be a huge amount of data, so maybe that's OK.

We may also have some options on the Keycloak side so to store this a separate records rather than comma-separated.  Looking into it.

**Comment by hkeeler** [comment]
I _think_ we can make this work using Keycloak's multi-valued attributes, rather than a single attribute with a comma-separated list value.  The result would be multiple values in the db, which would mean a simpler, more performant query.

The only unknown here is how to submit a multi-valued attribute on registration page.  It sounds like it can be done, though.
* https://issues.jboss.org/browse/KEYCLOAK-4376?focusedCommentId=13366581&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13366581

This _would_ mean a change to the access token, also going from a single string, to an array of values.  Fortunately, it looks like mod_auth_openidc already defaults to translating multi-valued attributes into a comma-separated string, so there shouldn't be any impact on how we handle authorization in the API.
* https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L612-L613

This seems like the right way to go.  I will create an issue in -auth to research further.  That said, we shouldn't hold up work on this issue while we figure that out.  We can always start out with the query you've proposed, and refactor if/when the Keycloak options becomes a reality.
