### ISSUE TITLE
Create regulator data stream

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#1283]
Provide mechanism to deliver daily dump of filing data (`Transmittal Sheet` and `Loan Application Register`) to regulators. High level requirements are as follows:

- Files will be automatically uploaded to an `Amazon Web Services S3` bucket
- `Loan Application Register` data is to be extracted daily at 10PM and made available as a single pipe delimited `csv` file, uncompressed, following the same format used at ingestion time as per the [Filing Instruction Guide](https://www.consumerfinance.gov/data-research/hmda/static/for-filers/2017/2017-HMDA-FIG.pdf). File naming convention will include time and date stamp following the [`ISO-8601`](https://en.wikipedia.org/wiki/ISO_8601) international standard.
- `Transmittal Sheet` data is to be extracted daily at 10PM and made available as a single pipe delimited `csv` file, uncompressed, following the same format used at ingestion time as per the [Filing Instruction Guide](https://www.consumerfinance.gov/data-research/hmda/static/for-filers/2017/2017-HMDA-FIG.pdf). In addition to this, a field will be appended at the end of each line (representing a single Financial Institution), with the date of latest filing. File naming convention will include time and date stamp following the [`ISO-8601`](https://en.wikipedia.org/wiki/ISO_8601) international standard.
- `Panel` data is to be extracted daily at 10PM and made available as a single pipe delimited `csv` file, uncompressed, following the same format used at ingestion time. 
- These processes should also be available on demand.

**Comment by Kibrael** [comment]
The FRB's ingestion process relies on the concatenation of Agency Code and Respondent ID, which is different from how our system is built. This requires that when they ingest LAR and TS data that each combination of Agency Code and Respondent ID be unique.

**Comment by jmarin** [comment]
@Kibrael Can you be more specific? What would we have to change in our data (if anything) to support this? What field(s) need to be added/modified and where? (compared to what is already published in [FIG](https://www.consumerfinance.gov/data-research/hmda/static/for-filers/2017/2017-HMDA-FIG.pdf), which is the official data model for HMDA collection).

**Comment by Kibrael** [comment]
@jmarin 

Background clarification: The Panel at FRB is built using the concatenation of Agency Code and Respondent ID as the institution ID. The Panel at CFPB is built using RSSD as the institution ID. 

When the Panel process at CFPB assigns an Agency Code and Respondent ID to an institution there is currently no check for duplicates for the FRB institution ID (Agency Code, Respondent ID). After speaking with @nickgrippin this seems like it may be more a of a Panel issue.

**Comment by Kibrael** [comment]
FRB also wants to ensure that all combinations of Agency Code and Respondent ID that are present in a LAR file are also present in the TS file.

**Comment by keileyo** [comment]
@Kibrael can you provide some clarification on the Transmittal Sheet requirement, specifically "ensure that all combinations of Agency Code and Respondent ID that are present in a LAR..."

While each individual LAR row contains a value for respondent ID and Agency Code, those values are the same for each row in the overall file, meaning that there is only one combination of respondent ID and agency code for each filer. This would be the same combination reported in the respondent ID and agency code data fields in the Transmittal Sheet.  

Is there a requirement from FRB to concatenate or otherwise manipulate those data fields in the TS or LAR files? If so, what is the source for that req

Let's keep discussion here to TS and LAR transfer requirements, and use the internal panel ticket for panel transfer requirements.

**Comment by Kibrael** [comment]
That LAR/TS format is good.
