### ISSUE TITLE
HmdaFileValidationState growing in size

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#1311]
This is the error in the logs. Investigate whether keeping that LARs in memory is necessary, or if a large number of submissions triggers this problem (witnessed on test data, with over 70 submissions).

`akka.remote.OversizedPayloadException: Discarding oversized payload sent to Actor[akka.tcp://hmda@10.95.36.18:12794/temp/$Zc1]: max allowed size 128000 bytes, actual size of encoded class hmda.persistence.processing.HmdaFileValidator$HmdaFileValidationState was 269313 bytes.`

**Comment by nickgrippin** [comment]
So, it looks like the only reason we're storing the full LAR in the state is in order to retrieve the relevant fields for a failed edit check in [`ValidationErrorConverter`](https://github.com/cfpb/hmda-platform/blob/master/api/src/main/scala/hmda/api/http/ValidationErrorConverter.scala#L66).  I'm currently investigating moving the field lookup and filtering into the `HmdaFileValidator` actor.

**Comment by jmarin** [comment]
OK, so maybe we can keep the list of `LAR` into a var in the actor, that gets updated when `LarPersisted` is triggered, but doesn't need to be part of `HmdaValidationState`.
