### ISSUE TITLE
Edit S040 response needs modification

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1322]
Users are reporting that edit S040, which is looking for duplicate loan/application IDs, is returning a confusing message when triggered. I am able to test and replicate the message. While the platform does correctly trigger S040 when there are duplicate IDs, the response states that the error is a blank loan/application ID, instead of the loan/application ID that is a duplicate. 

Users report thinking that this means they have a blank loan/application ID and are unsure how to fix the error without direction. 

![image](https://user-images.githubusercontent.com/13036571/32617770-eb044ac4-c543-11e7-8ef8-b5744852c87e.png)

**Comment by jmarin** [comment]
@awolfe76 Doesn't this one belong in `hmda-platform-ui`?

**Comment by awolfe76** [comment]
I think it needs some work here. There _may be_ some UI work too, but right now the response when `S040` is triggered looks like:

```json
{
  "count": 1,
  "total": 1,
  "edit": "S040",
  "rows": [
    { "row": { "rowId": "" }, "fields": { "Loan/Application Number": "error" } }
  ],
  "_links": {
    "self": "?page=1",
    "prev": "?page=1",
    "last": "?page=1",
    "next": "?page=1",
    "first": "?page=1",
    "href": "/institutions/6999998/filings/2017/submissions/3/edits/S040{rel}"
  }
}

```

We don't see the actual loan/application id there.

I think just making sure the `rowId` is there would be good. Then on the UI side, we'd just have to be sure to only render 1 column. Rendering the same column heading twice doesn't make sense here.

**Comment by awolfe76** [comment]
@keileyo - Are there other edits where we would be showing the loan/application id twice?

If there are we'll want to make sure

1. the API response for those edits is returning the `rowId` and
1. see if the UI needs to be updated to catch those edits and only render the column once.

**Comment by keileyo** [comment]
@awolfe76 that's right. Although it could potentially happen if the FI both duplicated the loan/id and the rows w/ duplicate loan/application IDs each contained the same validity or syntactical error (thinking that this could happen particularly if an FI accidentally duplicates an entire row).

**Comment by keileyo** [comment]
Ideally, the table would return:

1. The loan/application number that is duplicated
2. A message in the 2nd column stating "The loan/application number is duplicated in the HMDA file"

**Comment by awolfe76** [comment]
I'm fine with whatever message there but the one I had above, "Duplicate loan numbers reported; data already in file", came from FIG. At one point we had been trying to match those messages.

**Comment by schbetsy** [comment]
Speaking for the back-end here. I have bad news: We are severely limited by the architecture we currently have. Some background on how it works now:
 - `S040` can't work like a normal Syntactical edit. It's more like a Macro edit, since it has to look at the whole file to judge whether it passes or fails, not individual LARs.
 - As soon as it finds *any* duplicate loan number, it immediately fails. (So, whether there's lots of duplicated loan numbers or just one, it'll have exactly the same result). It doesn't record which particular loan made it fail.

I can only see two options (and only one seems reasonable with the timeline we have). I'd be happy to explain more, if that might help bring other options to light.
1. (LOE: no work for back end, moderate for front-end?): Change the ui for `S040` to make it look more like a macro edit. That is, don't show a table; just the edit description. The user would need to use their system of record or download the edit report to find the duplicate loan numbers.
2. (LOE: very high for back end, minimal for front-end): Re-implement `S040` so it can return the whole list of duplicated loan numbers. This would involve deep changes to the platform, including changes to the validation engine, as well as the way we report edit failures to the API. If we did this, (though it would allow us to give the user way better information about some failures, including macro edit failures) it would take a long time (like, more than a sprint).

Side note: the tables on the edit results page aren't designed to have explanatory messages in them. They're just designed to have values from the LAR. In our current design, the place for explanatory text is in the edit description, above the table. It would take significant work to change this pattern.

**Comment by keileyo** [comment]
Based on time and priority, I am in favor of the first option. Removing the table, and working with @awolfe76 on the messaging in the UI sounds like the way to go.

**Comment by awolfe76** [comment]
https://github.com/cfpb/hmda-platform-ui/issues/893 is created.

Do we think we can close this one for now?

**Comment by nickgrippin** [comment]
Closing ticket in favor of front-end approach.
