### ISSUE TITLE
Update 2016 LAR to parse NA correctly

### ISSUE THREAD

**Issue by ericspry** [cfpb/hmda-platform#1351]
The parser requires data loaded to the hmda platform to have properly formatted fields according to the data spec. Some historic 2016 LAR used for  Quality-Macro edit checks were not strictly formatted to the new parser spec. Task is to standardize these fields for loading to the platform.

**Comment by keileyo** [comment]
Fields that may be reported NA:
- Date Application Received 
- MSA/MD
- State Code
- County Code
- Census Tract
- Applicant Income
- Rate Spread

**Comment by wpears** [comment]
So is the transformation required to to remove `NA` in fields?

**Comment by jmarin** [comment]
@wpears No, although that might also happen (in that case, they are invalid HMDA files). The issue is that fields that might have NA in them need to have it correctly set. In many instances there will be values like `na`, `N/A`, `Not Applicable`, etc. which are all invalid as per the 2017 Filing Instruction Guide. I am not sure how many instances of these actually occur for 2016, but lowercase `na` and `N/A` is an issue that has popped up in the Beta period so those two are a good first guess for replacement. I expect this to be a sort of iterative process by which we fix most files and get through a smaller number of corner cases as we go along. Hope this makes sense.
