### ISSUE TITLE
Rate Spread calculator - issue in deployed environments

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#1385]
This issue is present in the beta production environment and in the HMDA3 release environment.

The rate spread calculator seems to be returning incorrect values. For example, given this input:
```json
{
  "actionTakenType": 1,
  "amortizationType": 30,
  "rateType": "FixedRate",
  "apr": 6.0,
  "lockinDate": "2017-11-20",
  "reverseMortgage": 2
}
```

it returns this: `{ "rateSpread": "6.0" }`
When we would expect this: `{ "rateSpread": 2.01 }`

This may be related to #1384, since both seem to indicate an issue with `HmdaPersistentActor`s not having the correct data when they start up.

**Comment by jmarin** [comment]
This is expected behavior. Data is loaded every Thursday at 11PM. For production, we don't have any files in the `S3` bucket yet (they need to be uploaded by Research). For `dev` there are some sample files.
This is unrelated to #1384. I am keeping this issue open until we test the workflow and are sure that the data transfer happens automatically.

**Comment by schbetsy** [comment]
Okay. My mistake. I had misunderstood how the calculator would get/store its values. I'll look back at the code.
