### ISSUE TITLE
Investigate and correct regulator data export formatting issues

### ISSUE THREAD

**Issue by ericspry** [cfpb/hmda-platform#1411]
For release 1.21 perhaps.. The following items have been reported in regards to the current regulator data export:

- [ ] Data in incorrect fields in the panel file:  
> the data in “email_domain_3” column should be in “respondent_name” column and so forth. The data in “parent_state” and “assets” columns should come from “'parent_city” column then you will have to split the text if there are 2 letters state abbreviation.

- [ ] Investigate panel data issues (could be related to the above): 

Missing fields?: 
•         id_rssd (RSSDID)
•         p_rssd (Parent RSSDID)

Corrections:  
*  Institution_Type should be institution type code but is showing institution type description

**Comment by Kibrael** [comment]
Removing the header email_domain_3 and shifting the remaining headers left fixed the header and data alignment issues. 

There is no pipe between parent_state and the assets field.

**Comment by keileyo** [comment]
@jmarin comprehensive list of the formatting issues with the raw panel file (in order of priority). I'll also provide you with a file containing the issues. 

1. The _parent_state_ field and _assets_ fields appear concatenated into a single field in the **panel data.** This does not apply to the panel file headers. The headers in the file show _parent_state_ and _assets_ as separate fields, and subsequent headers / data fields are off (i.e. _other lending code_ data appears under the _assets_ header and so forth)

2. The panel file export is missing _email_domain_3_ in the **panel data.** The data contains 2 email domain data fields (and therefore is missing the third email domain for any institutions that have three email domains).  The panel file **header** still contains the  _email_domain_3_ header, and the rest of the data is shifted left, so the _respondent name_ data appears under the header _email_domain_3_, and all subsequent headers / data fields are off. 

The two above are issues with the formatting of the file compared with the expected output. The two below are new requests from the FRB data team. 

3. Speaking of headers, FRB requested that headers be removed from panel, TS and LAR file outputs. 

4. FRB requested that the _inst_type_ be provided as integers instead of text. However, the scripts for loading panel into platform specify to convert the integers into text, so this seems like a lot of work and lowest priority.
