### ISSUE TITLE
Timestamp on signed submission is off 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1445]
Our test Bank 1 has a signed submission in production. @Kibrael noticed it in the data from the night of 1/11/18 and the timestamp on the signature is 2018-01-11T09:50:13.182. I signed up for a production account on Bank 1 on 1/12/18, and clicked "view completed filing" expecting to see the filing timestamp mentioned above, However, I saw a timestamp of January 12th, 11:14:57 AM which is the exact time I clicked on "view completed filing." Need to investigate if the issue is:

A. just generating a new timestamp incorrectly or 
B. if clicking on "view completed filing" can actually generate another submission of the data. 

![image](https://user-images.githubusercontent.com/13036571/34884552-0fd994d4-f78b-11e7-9f90-37c4f3835f44.png)

**Comment by keileyo** [comment]
@hkeeler can you check in splunk to see whether there was actually a signed submission for Bank 1 on 1/12/2018 at the timestamp in the comment above?

**Comment by schbetsy** [comment]
It seems the issue is [here in SubmissionPersistence](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/scala/hmda/persistence/institutions/SubmissionPersistence.scala#L37...L41).

When the actor replays the state, it assigns `end = now` instead of using the value it had before.

**Comment by schbetsy** [comment]
As we discussed yesterday, we don't have easy access to the actual time and date that previous submissions were completed. But we do want to assign a date and time to the ones that are finished, so that filers see a timestamp that shows they completed during the filing season (even if the date we assign isn't exactly right, they'll still know it wasn't turned in late).

@keileyo Do you care what time and date we use for the ones we don't know? We could default to any date (January 1, Feb 21, etc), we just have to choose one.

**Comment by keileyo** [comment]
@schbetsy I think it makes sense to default to a date that is close to when we implemented the fix for this. Does not have to be exact, but I think it makes sense to just go with the date that you get the PR in. That way we can always point back and say we defaulted all of those timestamps to the day that we resolved the issue.

**Comment by schbetsy** [comment]
Sounds great. I had a similar thought. The PR up now has the date set to today (Feb 21).
