### ISSUE TITLE
Large submissions: /edits/edit endpoint can time out

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#1466]
*#1450 improved user experience for large filers, but didn't solve all the issues. This is one issue that still exists after it is merged:*

For large file submissions, calls to `/edits/<edit>` are slow, and frequently time out. I believe this is because the edit response has to filter the event stream twice: once to get the 20 edits for that page of edit results, and again to find the 20 lars associated with those edits (to show the relevant data in the LAR that triggered the edit). This process is slow if there are a large number of edits and/or a large number of LARs.

**Comment by nickgrippin** [comment]
When the `/edits/{edit}` endpoint is requested for a filer with a large number of triggered edits, this error can be seen in the logs:
```
Ask timed out on [Actor[akka://hmda/user/supervisor/singleton/HmdaFileValidator-{submission ID}]] after [10000 ms]. Sender[null] sent message of type "hmda.persistence.processing.HmdaFileValidator$GetNamedErrorResultsPaginated".
```
This error message maps to the [`GetNamedErrorResultsPaginated`](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/scala/hmda/persistence/processing/HmdaFileValidator.scala#L276-L285) method in the `HmdaFileValidator`.

The method runs through the event stream, looking for all edits of a certain name (e.g. Q001).  Then, it runs through all those edits to retrieve a count, so it can calculate the indexes for the page number.  Finally, it runs through all those edits again to retrieve the subset specific to the page number.  In production, with a large filer, this method will regularly take longer than 10 seconds to complete, thus triggering the Actor timeout and the resulting 500 HTTP response.

A long-term solution, improving this method, is to reduce the number of times we loop through the list of edits.  
* The first potential approach is to keep track of the number of triggered edits in the `SVState` and `QMState`, while removing the call to `count(events)`.  Two downsides to this approach: it will have side effects (since we're changing the state), and it won't fix the problem with existing filers.  
* Another fix is to remove pagination from the edits endpoint, which will fix the issue of having to loop through the edits multiple times, but has the downside of an almost unusable UI.  
* One final long-term solution would be to split up the method, having the actor send itself a message to gather and count the edits, and then separately process the edits into pages.  This might get around the timeout by having the processing done in smaller chunks.

A short-term solution is to increase the actor timeout, allowing this method to potentially have time to complete.  There currently isn't an estimate for how long this method will take; some experimentation will be required.

I'm currently working on implementing the third bullet point, and will test out the approach once I have working code.
