### ISSUE TITLE
Date Application Received  -  V210 not always flagged when it should be

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1498]
Data team reported that unexpected values in the date application received field. V210 specifies _"Date application received must be in YYYYMMDD format; month and day must be in the range 01-12 and 01-31, respectively or equal NA. YYYY must be numeric and the first two digits of the number must equal 20."_  but certain values are not flagging the edit as expected: 2016121, 2017115, 2017089, 2017117

My theory is that the edit is not being flagged if the MM or DD value comes in without a required leading 0  (i.e. 2017117 is actually January 17th, 2017 and should be reported 20170117 **or** 2017117 is November 7th, 2017 and should be reported 20171107). Testing of this theory is ongoing (still need some info from the data team). 

Testing/Results:

- V210 is always returned if the entry is 6 digits or less (i.e.just 2017 or 201711 will flag the edit).
- The edit will be flagged if month and/or date are outside the expected range (i.e. 20179999 will flag the edit)
- The value 2016121 does not flag the edit, but 2016131 does. Currently its unclear if the initial intent of 2016121 is January 21, 2016 or December 1, 2016. Gathering more info.

**Comment by nickgrippin** [comment]
Here is the relevant line in our [codebase](https://github.com/cfpb/hmda-platform/blob/master/validation/src/main/scala/hmda/validation/rules/lar/validity/V210.scala#L16).  Notice how we set the format to be `"yyyyMMdd"`.

From the documentation on [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html): 
> For parsing, the number of pattern letters is ignored unless it's needed to separate two adjacent fields.

The month pattern is between two other fields, so the number of pattern letters is always 2.  Since the day field is not separating two other fields, the number of pattern letters is ignored.  Hence, 2016121 reads as 2016-12-1, which is valid.  However, 2016131 reads as 2016-13-1, which is invalid.
