### ISSUE TITLE
Number of 2017 filers discrepancy between API and CSV

### ISSUE THREAD

**Issue by charandas** [cfpb/hmda-platform#1567]
I am trying to understand the role of `hmda_filer` field in institutions csv?

Is it enrolled institutions, and some of these ended up not filing?

My script [here](https://github.com/charandas/hmda-tools) shows the difference.

**Comment by keileyo** [comment]
The institutions CSV was meant to be a comprehensive list of active institutions that were recognized by the platform for the purpose of filing HMDA data, knowing that the majority of those institutions would not qualify as HMDA reporters.   The filers endpoint represents the institutions that actually did file HMDA data for 2017. Most institutions in the filers endpoint are also in the CSV file, but there are some institutions that are not in the CSV because certain institutions were added or had their data modified during the filing period (additions and modifications are not represented in the institutions CSV).

**Comment by wpears** [comment]
Thanks Keiley!
