### ISSUE TITLE
Phase 1 - Dynamic LAR and TS files

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1581]
We have a publication requirement to make the full latest LAR and TS data sets available. 

**Timing:** LAR and TS data updated weekly, suggest producing weekly files on Sunday night. 

# Phase 1
## TS Data
Publish latest aggregate TS file w/ certain fields removed. 

Remove:

- Timestamp
- Contact Person's Name, Phone Number, Fax and Email 

## LAR Data
Publish latest aggregate LAR data w/ certain fields removed and appended. 

Remove:

- Application Date
- Loan/Application ID
- Action Taken Date

Format: 
- Pipe delimited text file 

Other requirements:
- Similar to modified LAR & reg data, we should block bank 0 & bank 1. 
- May need to block one FI's data due to the loan amt issue. Should have the capability to block or unblock certain institution's data from being included in the dynamic LAR & TS

**Comment by jmarin** [comment]
@keileyo Can we create two tickets out of this to reflect Phase 1 and Phase 2? It will be easier to track
Thanks

**Comment by keileyo** [comment]
Done, edited above and phase 2 is #1603

**Comment by keileyo** [comment]
DevOps issue # 728 lists info on blacklisting FI's data due to privacy issues.

**Comment by nickgrippin** [comment]
How often will institutions need to be blocked/unblocked?  Currently, in order to change the filtered status of any institution, we have to make minor changes to the code and redeploy the platform.  A small improvement would be to have the list of filtered institutions in an environment variable.  This would still require a redeployment of the platform, but wouldn't require any code changes.  The final possibility is to give the actor responsible for publication a state which would contain the list of filtered institutions, and create an API endpoint with the ability to modify that list.  
Of the three possibilities (as-is, env-var, or API), I think the environment variable would be our best bet, since it doesn't seem like we'll be modifying this list more than once or twice.
Also, do we want to have one file that gets overwritten weekly, or would we prefer to have a history of files, similar to LAR/TS/panel?

**Comment by keileyo** [comment]
I think the environment variable approach sounds right, at most blocking/unblocking would be a one-off request and will happen very rarely (will need to block bank 0, bank 1 & the one mentioned in the original ticket to start).

**Comment by keileyo** [comment]
Re question 2: Files can be overwritten weekly.
