### ISSUE TITLE
Census microservice

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2308]
Something to keep in mind is that this microservice can be used for both edits and publication (there may be other use cases). But, the immediate focus is to complete the remaining edits.

- [x] Pull / create the datasource
- [x] Load datasource
- [x] Code required to complete the edits

We'll be able to use the check digit microservice (coming soon) as a template for communication between 2 services.

**Comment by keileyo** [comment]
We are going to use the [2017 FFIEC census flat file](https://www.ffiec.gov/censusapp.htm) as the source, just paired down (there are 1,200+ variables!) to the information we need. We are using this file because 1) it already provides the crosswalk from census tract/county to MSA/MD (which is determined by OMB, not census); 2) it is the source for the ffiec [census reports product](https://www.ffiec.gov/%5C/census/default.aspx) which FIs use to check county/census tract/MSA/MD combinations.  

There are a couple of options:

1) pair down to just census tract, county, state and MSA/MD which is what we need in the short term for edits & IRS
2) pair down to census tract, county, state, MSA/MD + the 6 census variables that we append to the static & dynamic combined datasets. 

I think the 2nd makes the most sense - tables for the census microservice can be comprised of just the fields needed for the specific purpose, but then we don't need to create/upload another census file for the appended census fields which we will need later in the spring. @omnipresent07 @awolfe76 does that make sense to you guys?

**Comment by awolfe76** [comment]
I agree with the 2nd option.

**Comment by omnipresent07** [comment]
I agree, 2nd option makes sense to me as well.

**Comment by omnipresent07** [comment]
@keileyo 

1. Is the file in PR https://github.com/cfpb/hmda-platform/pull/2320 the one to be used for census microservice? We should close that PR and put the file in collab. I believe the plan is for us to take the data from that TXT file and insert it into postgres. 
2. Is there a list of edits that will be dependent on the census microservice (similar to `V609` being dependent on the checkdigit microservice?)
3. It would also be good to understand the logic needed for each edit to be implemented. [LAR spec file](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_File_Spec_LAR.csv#L20) has field 18 that is census tract. Are we going to match that with census tract in the `new_2018_HMDA_Census_fields.txt` ?

<img width="1004" alt="screen shot 2018-12-10 at 5 39 13 am" src="https://user-images.githubusercontent.com/44377678/49727357-0d882c00-fc3e-11e8-8f7c-74bee4f00540.png">

**Comment by keileyo** [comment]
1. The file is also in drive

2. Yes, those are the correct edits that are dependent on census

3. The logic is going to need to be a little bit different. 
- Reporting the HMDA data, census tract is actually 11 digits (2 digit FIPS state code + 3 digit FIPS county code + 6 digit census tract number).  So for V625-2 for example, youll be looking to see if the 11 digit value provided in the field matches a valid combination of state, county & census tract in the census fields table.  
- Same goes for county - you are looking to see if the 5 digits provided is an actual valid combination of 2 digit state & 3 digit county from the census fields table 
- for V627, you don't actually need the census fields table. In this one, you are just checking to be sure that the 5 digits reported in the county field are the same first 5 digits of the 11 digit census tract field. 

Let me know if you want to talk more about the logic, happy to.

**Comment by keileyo** [comment]
Q603 and Q604 are also census edits. We will need to talk through Q603 i think.
