### ISSUE TITLE
IRS Report

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#2343]

**Comment by keileyo** [comment]
In order to generate the IRS this year, we will need to reference the MSA/MD which is part of the census data used for the census microservice. 

We will have census tract information in the data & the census tracts will need to be rolled up into MSA/MD. Otherwise, the format/information should remain the same.

**Comment by awolfe76** [comment]
@nickgrippin - from our conversation about the location of the IRS in S3, and from [this PR](https://github.com/cfpb/hmda-platform-ui/pull/1225) ([this line](https://github.com/cfpb/hmda-platform-ui/pull/1225/files#diff-939d7779f91b93eda7b6f46125063e35R20)), the reports should live at 
```
https://s3.amazonaws.com/cfpb-hmda-public/prod/reports/disclosure/2018/<lei>/nationwide/IRS.txt
```

The change being the year, `2018`, and now using the `lei`.

**Comment by keileyo** [comment]
The fields reported are different than last year, which requires a couple of changes to the IRS structure:

1) Property Type is no longer reported and was split into Construction Method and Total Units.
- Column for Construction Method:
Code 1 - Site-built
Code 2 - Manufactured Home
- Column for Total Units w/ 2 categories (total units is reported in whole numbers). Categorize into:
1-4 units
5+ units

2)  Codes for Loan Purpose are different:
Code 1. Home purchase
Code 2. Home improvement
Code 31. Refinancing
Code 32. Cash-out refinancing
Code 4. Other purpose
Code 5. Not applicable
