### ISSUE TITLE
Macro / Quality edits verification & nav is off 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2370]
Testing files that have macro edits, I'm seeing the following behavior:

- Quality edits default to being verified
- Button to move forward to review macro edits is missing. 
- Nav bar on top does NOT show quality edits as verified & therefore cannot move forward past quality edits

Quality edits default to verified w/ no nav button:
![image](https://user-images.githubusercontent.com/13036571/50125065-41161800-0235-11e9-92d7-ad06b239f9fb.png)

Nav bar:
![image](https://user-images.githubusercontent.com/13036571/50125092-59863280-0235-11e9-94af-cb8455a58ec9.png)

**Comment by keileyo** [comment]
Follow up:

- Selecting "filing home" and then navigating back to the quality edits page clears the verification. I then genuinely verified quality edits & moved to macro edits

**Comment by wpears** [comment]
I can repro this by verifying quality then immediately re-uploading a file. When doing so the `verified` flag for the new edits returns `true` (when it should be `false` for all new submissions where edits exist).

I imagine the `verified` state is not getting flushed immediately across submissions and the asynchronous nature of the operation is causing it to fail at first but work eventually (which is why you see it operate correctly after making another call to the edits endpoint by navigating away and back).

Fix would involve making sure that the verified state is reset by the time it's needed (possibly holding off on a response to the `/edits` endpoint if the verified state flush hasn't completed.
