### ISSUE TITLE
Edits details table populating w/ the wrong values for some GMI fields 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2478]
The edits details for V655 - 1 are wrong. I _think_ the edit is flagging appropriately, but the details table is pulling in the wrong values for the involved Race, Ethnicity and Sex fields. See example of NULI 3LEJBDON10PPP3GXMO4BYF below (file is attached)
[v655 - test 2.txt](https://github.com/cfpb/hmda-platform/files/2733608/v655.-.test.2.txt)

Actual values for Race, Ethnicity & Sex of Applicant:1 highlighted:

![image](https://user-images.githubusercontent.com/13036571/50782373-cc535e00-1275-11e9-92ba-65e8469d93f1.png)

Values displayed in the edits table. Instead of a 4, the Sex of Applicant or Borrower is showing as a 3, and instead of 7, the Race of Applicant or Borrower:1 is showing 1. 
![image](https://user-images.githubusercontent.com/13036571/50782264-8c8c7680-1275-11e9-891d-760f5d085f38.png)

In this case, the edit is being flagged appropriately because the actual values in the file should trigger the edit, but the edits details table is pulling information from somewhere else making it look like the edit should not flag.

**Comment by keileyo** [comment]
here is a file that produces the same issue:
- V636-3- the second record is trying to pull the  Race of Applicant or Borrower: Free Form Text Field for Other Asian into the Race of Applicant or Borrower: 3 edits table field. 

[v655 - test 2.txt](https://github.com/cfpb/hmda-platform/files/2738410/v655.-.test.2.txt)

**Comment by kgudel** [comment]
This behavior is due to the edits details list being returned in an arbitrary order that can change between returned rows. Because the -ui expects all returned rows to have their details ordered in the same way rows after the first may appear to be scrambled.

Addressing this should also fix: #2495

**Comment by chynnakeys** [comment]
HMDA Help Ticket discovered another edit that displays this behavior V676-5

![image](https://user-images.githubusercontent.com/41752348/52042771-fb26c200-250b-11e9-860b-5820d3277dc0.png)

As you can see, there is a mismatch between the fields displayed on the platform vs the fields displayed on the spreadsheet. They are unable to proceed past this point because of the mismatch it seems.

![image](https://user-images.githubusercontent.com/41752348/52042795-07ab1a80-250c-11e9-9e75-b2c7c820cba7.png)
