### ISSUE TITLE
Throw Parser error for rows ending in | (Pipe Character)

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2560]
After trimming the lars if any row ends in `|` we should throw a parsing error

**Comment by keileyo** [comment]
Have we made other changes to the parser besides this? a number of our test files are now throwing unexpected parsing errors on HMDA4, and im not sure if the root cause is related to these parser changes or something else (these are not files that contain an extra pipe character). 

Example: 
[Bank 0 101 LAR Q600.txt](https://github.com/cfpb/hmda-platform/files/3035272/Bank.0.101.LAR.Q600.txt)

**Comment by keileyo** [comment]
Disregard comment above
