### ISSUE TITLE
ULI validator validates invalid checkdigit 01

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#2623]
If a converted LEI is perfectly divisible by 97, the correct check digit is 98.  However, if the LEI is used with check digit 01, the validator will return Valid.  The validator should always return Invalid if the check digit is 01, since the range of valid check digits is 02-98:
  * `x = LEI mod 97` can be 0 though 96  
  * `y = 98 - x` can be 2 through 98

You can test it by validating `97000000000000000000001` and `97000000000000000000098`

**Comment by keileyo** [comment]
Thanks for commenting. The check digit tool uses the match outlined in Appendix C of the HMDA regulation: https://www.consumerfinance.gov/policy-compliance/rulemaking/regulations/1003/C/

Check digit validation, after converting letters to numbers, applies the `mod 97` operation and checks is that the value is 1. However, since 00 and 97 are separated by exactly 97, they result in the same result so both will be valid.
