### ISSUE TITLE
Describe Persistence requirements (File Submission)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#264]
The HMDA Platform has a strong requirement for managing the state of the submission process. A HMDA Submission can be in one of the following states: 

1. Uploaded to the system: the user has **sent** the HMDA File to the system for validation
2. Parsed: the file has been **parsed** and found to be structurally correct as per the File Spec. If errors are present, they need to be corrected and the file resent. 
3. Valid: the contents have been **checked** for correctness and validity, and the submission is ready to be verified by the user.If there are syntactical or validity errors, the user must correct them and resend the file.
4. Checked: the information has been **validated** for consistency with macro and quality errors, and needs input from the user to explain the edit errors found. 
5. Verified: the user has **verified** the results of the macro and quality errors
6. The user has sent **signed** confirmation that the information is correct and has been verified. 

Every time a file is sent again during the submission process (or as a result of resubmissions) the process starts from step 1) above. 

From a system perspective, for each submission we want to store the following information: 

1) Raw data sent to HMDA Platform. The contents of the information sent by the FI are stored in their original text format. 
2) Parsing results. Store the results of the parsing operation (especially errors). 
3) Syntactical edits (errors)
4) Validity edits (errors)
5) HMDA content is checked (passes syntactical and validity)
6) Quality edits (errors)
7) Macro edits (errors)
8) Justification to Quality edits (persisted individually)
9) Justification to Macro edits (persisted individually)
10) HMDA content is verified (by user providing feedback about macro/quality errors).
11) Edit reports (IRS, Summary report, etc). Triggered by previous step
12) Submission verified (signed) by user

Steps 1-6 are triggered without user intervention, with one exception: if the parsing fails, the HMDA File needs to be corrected and resubmitted. The file will also need to be resubmitted in case of a system failure in step 1. Steps 8-10 and 12 require user input to proceed. 

The system must provide a **full audit trail** of the process. It needs to log every partial, incomplete or invalid submission and persist errors for reporting to the user and further analysis.

**Comment by lesgou** [comment]
1. "Valid: the contents have been checked for correctness and validity, and the submission is ready to be verified by the user.If there are syntactical or validity errors, the user must correct them and resend the file."  
To clarify, does this mean that there are two "stages" of validation? The first is through the syntactical and validity edits, and will need the user to upload a new file. And the second is after the quality and macro edits, prior to the user's verification of each edit?


2. "11) Edit reports (IRS, Summary report, etc). Triggered by previous step"
To clarify, is edit report referring to the reports that are triggered at the end, after all the edits have been dealt with by the user? The term "edit report" may be confusing because today, it is used for the pdf with all edits, including the confirmation sheet/signature.

**Comment by jmarin** [comment]
@lesgou To your first question, the answer is yes. This second "stage" happens automatically, **only if** the syntactical and validity pass. It's a way to store the state of the different types of edits. We could break this down into 4 stages: syntactical, validity, macro, quality if that is easier and aligns better with what how the edits are really broken down. So all edits would happen automatically, but macro and quality would only be triggered if the first two pass. 

I've used "edit report" very liberally here, more as a concept for encompassing everything that is reported after a validation run. Maybe we need a different name for this since it causes confusion? The reason for separating verification from "signature" is because those functions could be done at a different point in time, by a different person. When a "signer" comes back and logs in, we need to show that all edits have been "verified" through summary statistics and reports. 

Hope this makes sense.

**Comment by awolfe76** [comment]
> Steps 1-6 are triggered without user intervention, ...

I think you mean steps 1-7, right?

>So all edits would happen automatically, but macro and quality would only be triggered if the first two pass.

We had talked about running all edits no matter what so that we give the filer a full report. So all checks happen during each upload of a file, unless it fails to parse. The thought was that the full report may help them correct errors and they get the full report back today. The more information they have the better. They just would not be able to verify quality and macro until syntax and validity are ok, storage point 5) is true. This is also where we talked about possible performance issues but since we really don't know it was ok for now.

**Comment by lesgou** [comment]
@jmarin Thanks for the clarification. I'm good with the definition of "valid", and good with having "edit report" mean everything except for signature.

@awolfe76 I think we did talk about having the full report before. Does this also relate to the possibility of a partial file submission? And whether the fi would have all edits run, including macro, even if 1/12 of the loans are uploaded.

**Comment by awolfe76** [comment]
Are we allowing for partial uploads?

**Comment by jmarin** [comment]
@awolfe76 This has come up very recently again from a couple of directions. I think we can't allow it unless we significantly change the File Spec. For partial submissions, you want to have a description of what has changed. Every record should be flagged as `added`, `modified` or `deleted` so that we can treat the partial information accordingly. This would allow submission of "delta" files (only what has changed). But the current File Spec, inherited from the process and quite tied to the regulation is limiting us here. 

The other type of "partial submission" is when someone files a subset of the total (i.e. one month). It's just too dangerous to assume that we will get 1/xth of the information and that it will all add up, imho. Some organizations work that way and this model will fit them, but it can be very confusing to others I think.

**Comment by jmarin** [comment]
@awolfe76 @lesgou We can run all validations and provide a preliminary report. Not concerned about performance until we measure it, so that initial assumption is as good as any other. Thanks for the feedback

**Comment by awolfe76** [comment]
Thanks @jmarin.

And I agree on the partials. It's a big change from the "all at once" approach we've been talking about.

**Comment by debseidner** [comment]
@jmarin Agree with Leslie and Andrew that we need to keep a copy of the full edit report - or all the data every time submitted so one could be compiled on the fly - as the FIs will need to be able to save a PDF copy of the full edit report like they get today for their records. This is checked during exams from what we can tell.

**Comment by wpears** [comment]
Due to the possibility of error at *any* stage, I'd break down the states a bit more:

*begin*
1. Submission created
2. File begins uploading
3. File upload complete
4. Parsing begins
5. Parsing completes
6. Validation begins
7. Validation complete, with syntax/validity errors (requires restart)
8. Validation complete, no syntax/validity errors, but with unverified quality/macro errors
9. Validation complete, no syntax/validity errors, no unverified quality/macro errors
10. Verification submitted
11. Verification recorded
*done*
(steps 7 and 8 would be skipped if no errors of any kind were found)

If an error crops up at any point an `error` state could be pushed on that would help identify exactly what happened during the submission process. This would also apply to a `cancelled` state that gets applied if the user manually cancels submission (via an api endpoint, say, when a user realizes a mistake right after uploading and wants to resubmit.. this exists in the UI right now as a resubmit link that calls the cancel endpoint and routes to the upload component).

**Comment by debseidner** [comment]
@wpears With this breakdown, are you suggesting that persistence only occurs after each of the 11 steps? The reason I am asking is that we need to be able to persist individual quality/macro error responses so if we break it down that way and you meant that for persistence, I don't know if that could be done with that construct.

**Comment by wpears** [comment]
@debseidner I'm strictly describing my take on the states of submission. Persistence could and likely should be handled between these states. For example, as validation begins, results get streamed from the validation engine and persisted, even though the submission as a whole hasn't moved on from my proposed state 6. Similarly, a user may submit a justification for one out of seven quality error, that justification would be persisted but wouldn't move the submission from state 8 to state 9 until all justifications are complete. So really just an expansion of Juan's 6 states above with explicit starts and ends to states for clarity.

**Comment by jmarin** [comment]
@wpears @debseidner I think....both of you are right :)
