### ISSUE TITLE
Bank 0 clean files failing parsing (Cassandra is out of sync with submission ID)

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#2717]
This appears to be a problem with the bank 0 test files.

Bank 0 file formatting appears fine (passes the file format verification tool). This issue would then require an analysis of how the platform is processing the Bank 0 file.

**Comment by keileyo** [comment]
This is a known issue w/ the institution Bank  0, not the test files. The same test files will parse uploading to a different bank. 

I _think_ we've discussed before and this is related to not being able to delete submissions.

**Comment by omnipresent07** [comment]
Yes, platforms' submission id numbers for Bank0 are out of sync in cassandra. Because of this any new file being submitted is being appended to a previous record. 

This is related to https://github.com/cfpb/hmda-platform/issues/2215 . We need a /delete endpoint that cleans up the institution in cassandra.

**Comment by omnipresent07** [comment]
This has been fixed and can be verified. There was no PR required. The Bank0 sequenceNumber of submissions had to be updated.
