### ISSUE TITLE
Provide an and vs. or option in data-browser

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2842]
@wpears brought up a good point about the data-browser API. 

Use Case: While doing multi geography selection, user wants to view results for entire CO state as well as some msamds in CA. In its current design the user would have to download two CSVs via the front end -- first for statewide CO and second for some msamds in CA. 

Alternative: This is because when state and msamds are passed in, the backend performs an `AND` operation. An alternative option could be to allow the users an option to pick an `AND` vs. `OR` or always perform an `OR`.

**Comment by wpears** [comment]
My opinion on this is that adding the ability the select multiple geographies strongly implies that the query would return data in the entire two areas. I think the original implementation detail of using an `AND` between state and msamd to get the correct geography has bled into the API in an unintuitive way now that we've allowed multi-geography selection.

Moreover I'm not really in favor of the language of `AND` vs `OR` in the frontend, I think we might get away with something like filter vs. include, but I think it would be better to figure out how most people are using/thinking about the data and designing it to serve those behaviors.

Ultimately, we're forced to make a tradeoff one way or another with `AND` vs `OR` behavior because the API isn't super expressive in how it models geography. Namely, there isn't a way currently to associate a single "geography" with both state and msamd identifiers. This leads us to a situation where it's either impossible to pick statewide geographies at the same time as msamd-bound geographies (the current situation) or impossible to pick only specific parts of a multi-state msamd (the behavior until an `OR` model). These two behaviors *could* both be supported but it would require changing the api to allow associating both state and msa with a geography, eg.

`/data-browser-api/view/aggregations?geographies=11244,17020,CO,TN~32820&races=Joint`

which would get data in the Anaheim and Chico msa/mds in California, all of Colorado, and just the Tennessee portion of the Memphis msa/md. The grammar here is comma-separated geographies which each can either be the 5 digit msamd, the two character state code, or a tilde-separated combination of both.
