### ISSUE TITLE
Update platform-ui for multiple years

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#2864]
[Reference Ticket for HMDA Platform UI](https://github.com/cfpb/hmda-platform-ui/issues/1254)

**Comment by chynnakeys** [comment]
@BarakStout the years should display after the user logs in. Additionally, can we switch the placement of 2018 and 2019 so that 2019 is the default year

**Comment by wpears** [comment]
There are a couple problems with not displaying the year selector on the homepage:
  - we have to have the current year in the url, since `/filing/` is taken by v1. This means that before a user logs in, they can see that they're set to file for the latest year (we also include the year in the header ie **Get started filing your 2019 HMDA data**). This could cause confusion for people who are refiling ("I don't want to file for 2019, how do I get to a different year?")
 - We may want different content for different years on the homepage, eg pointing to different resources or talking about quarterly filing or not. Having a year selector on the homepage allows an easy way to switch between these different pieces of content (vs burying links to different versions in a list at ffiec.cfpb.gov)
 - keycloak needs a redirectUri to know where to bring the application back to on a successful login. This needs to have the year included and on a successful login, institutions for that year are automatically requested. Without allowing a user to select the year they care about before logging in, those requests will be unnecessary and possibly confusing (like if an institution a user is filing for doesn't exist in the current year but has in the past, they'd get errors before being able to select the year they care about).

**Comment by chynnakeys** [comment]
@wpears understood, let's disregard my first comment then. Would the second be feasible?

**Comment by wpears** [comment]
Yep, PR here https://github.com/cfpb/hmda-platform-ui/pull/1266
