### ISSUE TITLE
Creatively add a header in modified lars generated for 2018

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2983]
2018 modified lars are generated and CSV file are on S3. However, these files do not have a header. Look at ways whether we can add a header at the time of serving the file from the platform.

**Comment by omnipresent07** [comment]
all of the files are in a new S3 bucket: s3://cfpb-hmda-public/prod/modified-lar/2018/header/<lei>_header.txt

**Comment by meissadia** [comment]
Hey @omnipresent07,

Can you please update the `Content-Disposition` of these files to `attachment`?

[AWS UI](https://docs.easydigitaldownloads.com/article/1172-how-do-i-force-files-to-download-in-amazon-s3) | [AWS CLI](https://forums.aws.amazon.com/thread.jspa?messageID=677818)

Currently,  when accessed from the UI, the files are loaded in the browser as plain text instead of being downloaded. 

Thanks.
