### ISSUE TITLE
Email Table Update for Institutions Unique to 2019 Bug

### ISSUE THREAD

**Issue by PatrickHSI** [cfpb/hmda-platform#3250]
There is an issue in which institutions unique to 2019 ( no 2018 institution table record)  email domain data isn't getting inserted into the postgresql email table.

**Comment by omnipresent07** [comment]
This issue is because of a foreign key constraint in `institutions_emails_2018` on `institutions2018`. When a new institution for 2019 is added, the platform sends a kafka record in the `institution` topic. This record gets picked up by the `institutions-api` which inserts the record in `institutions2019` PG table and `institutions_emails_2018` table. However, the insert into the `institutions_emails_2018` fails because of the aforementioned foreign key. The fix here would be to 1) delete the foreign key relationship and 2) rename the `institutons_emails_2018` table that better reflects its meaning (since it is no longer just for 2018). I would propose we do (2) later as it will have rippling affects elsewhere.
