### ISSUE TITLE
Edit Reports not downloading in Beta

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3277]
Upon trying to download the quality edit report, an error displays: 

![image](https://user-images.githubusercontent.com/41752348/69555073-82ad5800-0f9a-11ea-916d-83e4cab12c84.png)

**Comment by omnipresent07** [comment]
The front end is making a request to `/filing/institutions/B90YWS6AFX2LGWOXJ1LD/filings/[object%20Object]/submissions/7/edits/csv?format=csv` which seems incorrect. @meissadia @wpears

**Comment by meissadia** [comment]
Not able to reproduce locally.

On `ffiec.beta` the `fetchCSV` action is receiving `submission.id.period` that is an object with quarter and year instead of just a string for year.  

local
<img width="392" alt="local" src="https://user-images.githubusercontent.com/2592907/69564259-ea9a7900-0f6f-11ea-87c5-2e8a16e968e5.png">

ffiec.beta
<img width="401" alt="ffiec beta" src="https://user-images.githubusercontent.com/2592907/69564279-f1c18700-0f6f-11ea-8687-81e8b492bcaf.png">
