### ISSUE TITLE
Akka cluster should still be able to connect to the cassandra cluster if one of the cassandra nodes is down

### ISSUE THREAD

**Issue by zencircle** [cfpb/hmda-platform#3468]
It is ideal if the Akka cluster is able to connect to the cassandra cluster even if one of the cassandra nodes are down.

**Comment by omnipresent07** [comment]
To re-create this - bring one of the 5 cassandra nodes down and restart the platform. The cluster should still form.

**Comment by omnipresent07** [comment]
The platform on dev works OK when one of the five cassandra nodes are down. There will be errors in the logs since as a round robin policy one of the five nodes is down, however, the platform will continue to work as expected. The config map `cassandra-hosts` must be changed to point to a node that _is_ up.

**Comment by omnipresent07** [comment]
When one of the 5 nodes is down, the round robin policy for cassandra should not report that there are 5 nodes. It should rather report that there are 4 nodes so that the platform doesn't try to connect to the damaged node.
