### ISSUE TITLE
Test 2020 Edits

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#3912]
Test the newly created edits for 2020

**Comment by audayshankar** [comment]
V602 - (Invalid calendar quarter was reported) This edit does not trigger.

V600 - The description of the warning does not appear 

  ![image](https://user-images.githubusercontent.com/58990254/99983863-69d8ad80-2d7a-11eb-9eaf-32257dddcccd.png)

S304 - LEI does not appear, only the words "empty-uli" 

   ![image](https://user-images.githubusercontent.com/58990254/99983895-75c46f80-2d7a-11eb-9cb6-bd253f17c7bb.png)

**Comment by audayshankar** [comment]
**Testing in hmda4 beta**

V716 - Edit does not have a description and does not display the state/county that is being reported as incorrect, like the other edits do.

![image](https://user-images.githubusercontent.com/58990254/101065188-dade4900-3562-11eb-8dba-8cdff49ce26e.png)
[Abhinayaa Bank_5_v716.txt](https://github.com/cfpb/hmda-platform/files/5637831/Abhinayaa.Bank_5_v716.txt)


S306 - Error display in the ULI data field

![image](https://user-images.githubusercontent.com/58990254/101066285-3230e900-3564-11eb-81ba-238b2f732164.png)
[Abhinayaa Bank_S306.txt](https://github.com/cfpb/hmda-platform/files/5637886/Abhinayaa.Bank_S306.txt)

**Comment by audayshankar** [comment]
**Testing in hmda4 beta**

S305 - Same issue that was happening above in S304. "empty-uli" appears in LEI data field.
![image](https://user-images.githubusercontent.com/58990254/101196188-67a20900-362e-11eb-81e0-f1adc7f13daf.png)


v608 - How does V608-1 get triggered / How does platform differentiate between ULI/NULI? 
I left ULI blank and I received V608-2, but having trouble getting V608-1 to trigger.
Tried input "z" & "0" as ULI, does not trigger - 
[Abhinayaa Bank_V608-1.txt](https://github.com/cfpb/hmda-platform/files/5644431/Abhinayaa.Bank_V608-1.txt)

![image](https://user-images.githubusercontent.com/58990254/101196858-4d1c5f80-362f-11eb-9611-b1779715d977.png)

@chynnakeys Any insight on what triggers V608-1?

**Comment by audayshankar** [comment]
Second round of testing on hmda4-default:

V602 is resolved.

Q600 is resolved but two minor adjustments needed. Capitalize the "T" in there and add a period at the end of the warning.
![image](https://user-images.githubusercontent.com/58990254/101793849-3c0e9b00-3ad4-11eb-815f-3dc1791d0163.png)

Issues indicated in above comments still appearing with S304, V716, S306, S305.

**Comment by audayshankar** [comment]
All comments above have been resolved except for the below: 

Q600 Warning - Adding a period "." to the end of the sentence
![image](https://user-images.githubusercontent.com/58990254/102519230-37139380-4060-11eb-883f-a24a6b35e72a.png)
[Abhinayaa.Bank_Q600.txt](https://github.com/cfpb/hmda-platform/files/5711030/Abhinayaa.Bank_Q600.txt)



S306 - It looks like the LEI field is pulling the ULI from the file, instead of the LEI.
![image](https://user-images.githubusercontent.com/58990254/102519460-7fcb4c80-4060-11eb-82c2-30e670a95eed.png)
[Abhinayaa Bank_S306.txt](https://github.com/cfpb/hmda-platform/files/5711017/Abhinayaa.Bank_S306.txt)


V608 -  The ULI column is showing up twice and only needs to show up once (should look like what is pictured for V609)
![image](https://user-images.githubusercontent.com/58990254/102519802-f49e8680-4060-11eb-9d50-18ff84666fce.png)
[Abhinayaa Bank_V608-1-uli 48 character.txt](https://github.com/cfpb/hmda-platform/files/5711032/Abhinayaa.Bank_V608-1-uli.48.character.txt)

**Comment by PatrickGoRaft** [comment]
@audayshankar  V609 had a similar issues that was resolved via frontend fix.  I'll open a ticket to resolve it there. 

https://github.com/cfpb/hmda-frontend/pull/368

**Comment by audayshankar** [comment]
All remaining issues appear resolved.
