### ISSUE TITLE
new dashboard queries 

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#4004]
Add a query to dashboard that fetches number of LARs less than a Number. The number can be configurable by the query parameter / frontend

```
select count(*) from transmittalsheet2020 where total_lines < 100;
```

**Comment by ericspry** [comment]
Four new stats: 
1. Total voluntary filers (filers with < 100 LAR 
2. < 100 closed end in each of preceding two
3. < 500 open end loans in each of preceding 2 years
4. < 200 open end loans in each of preceding 2 years

**Comment by Kibrael** [comment]
**Voluntary Filer Definitions**
1) Voluntary is defined as reporting when reporting is not required under Regulation C for *either* open or closed-end data as these are checked independently.

2) Voluntary reporting is also defined as reporting of data for which a depository institution was eligible to claim a partial exemption due to having a passing CRA rating and originating fewer than 500 closed-end loans in each of the preceding two calendar years.



Proxying voluntary reporter status is necessary because not all the required criteria can be checked.

1) Filers with < 100 LAR records as a proxy for closed-end threshold check
2) Filers with < 100 Closed End Originations in either of the preceding 2 years (coverage requires both meet threshold)
3) Filers with < 500 Open End Originations in either of the preceding 2 years (coverage requires both meet threshold)
4) Filers with < 200 Open End Originations in either of the preceding 2 years (coverage requires both meet threshold)


**Potential Data Output:**
|Name|LEI|LAR Count|Origination Count|Closed-End Origination Count|Open-End Origination Count|Exempt Count|Depository Status|
|----|---|---------|-----------------|----------------------------|--------------------------|------------|-----------------|
|Bank 0|LEIFORBANK01235|500|300|100|400|Y|
|Non-Bank 1|LEIFORNONBANK11235|300|300||0|N|


Definitions:
- Origination: Action taken = 1
- Open-End: line-of-credits = 1
- Closed-End: line-of-credits = 2
- Exempt: line-of-credits = 1111
- Depository status:
	- DI: institution type code < 8
	- Non-DI: institution type code >= 8

**Comment by ericspry** [comment]
Per annual filing season, unique filer count and LAR count for:

1. Less than 100 closed end originated loans
`Open-End Line of Credit = 2 AND Action Taken = 1`

2. Less than 200 open end originated loans
`Open-End Line of Credit = 1 AND Action Taken = 1`

3. less than 500 open end originated loans
`Open-End Line of Credit = 1 AND Action Taken = 1` 

4. Less than 100 originated loans - exempt
`Open-End Line of Credit = 1111 AND Action Taken = 1`

Not grouped by Agency.
