### ISSUE TITLE
Research: explore LAR data in Kafka along with submission ids for down stream processes

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/hmda-platform#4398]
Explore having LAR data in Kafka readily available for downstream processes instead of just submission ids

**Comment by PatrickGoRaft** [comment]
@lchen-2101 

From our original  thoughts on this , we were considering putting the entire uploaded file into a value of a single Kafka record. However, these might be quite large - in the order of 100s of MBs. Kafka isn't designed for large messages - the default max size of a single message is 1MB. It can be increased, but not significantly.

Instead, we could produce each LAR as a separate Kafka message. On one hand, this would give us a very nice, low-footprint streaming solution, as we could stream the LARs from Cassandra to Kafka without ever reading the entire dataset into memory. On the other, we would need to solve some challenges, such as keeping the LAR order (if it's significant), knowing when a new submission starts and when it ends.

Firstly, all LARs for a single submission should go to a single partition, so that any consumers read them in the same order as they were produced. Secondly, we'd need to know when the entire submission has been received by the consumer. To do this, we would need to first produce a "header" message (sth like TS), which would include the submission id & expected lar count. Each subsequent LAR message would need to include the submission id + sequence number (the consecutive LAR number, that is line number in the file - 1). This would also allow consumers to react correctly in case a LAR message get duplicated (which can always happen for a number of reasons).

Another important aspect to consider is what about failures - what if the LAR-producing process stops before being complete (e.g. server crash)? Should we restart the producer? I suppose this can be done quite straightforwardly with Akka Persistence & a new command. This would mean, however, that in case of a failure, the process would start anew - and a consumer would have to accommodate for that (it would have to be prepared that a submission might be transmitted again from the beginning).

Finally, there's the concurrency problem. What if there are multiple submissions happening at once? We'd of course try to spread the submissions across Kafka partitions, but it's still quite probable that two submissions might end up on a single partition. Here again, the consumer would have to take into account the message keys, which would include the submission id & the offset, and react accordingly.

With the data streaming work being done by our data team, this may be a redundant effort.  I'll discuss things with the team.
