### ISSUE TITLE
Search Functionality in BETA 

### ISSUE THREAD

**Issue by offoaro** [cfpb/hmda-platform#4550]
When searching for institutions in beta, there's no drop-down loaded up for institutions from a-z, only 2 institutions are in the drop down ( test bank and bank0). You can still search for institutions by their LEI's but that is the only way you can locate them.

**Comment by meissadia** [comment]
Possibly missing routing for `/v2/reporting/` for Beta?
- `GET https://ffiec.beta.cfpb.gov/v2/reporting/filers/2022` -> Returns HTML instead of JSON
  -  Implies that this request is getting routed to the Frontend instead of the Platform

Other API routes are working as expected, so this is not likely to be a Platform issue
- `/v2/admin/`
- `/v2/filing/`

**Comment by meissadia** [comment]
The /v2/reporting service does not run in Prod Beta.  

Since the API is only used by HMDA Help to present a list institutions, Bhargav has routed these requests to the Prod default service. 

Initial testing looks good.
<img width="1116" alt="Screen Shot 2022-11-16 at 11 39 36 AM" src="https://user-images.githubusercontent.com/2592907/202266217-4e3ba50a-dd58-40fc-b7e5-b399c29b594a.png">

@offoaro Please verify that you are able to see the Institutions listed in the search box on Prod Beta.

**Comment by meissadia** [comment]
Verified as fixed 👍🏽
