### ISSUE TITLE
Quarterly Graphs Verbiage update

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/hmda-platform#4582]
update quarterly graphs verbiage for subtitles

**Comment by audayshankar** [comment]
New verbiage can be found here: [Quarterly Graphing Tool Subheading Updates](https://bcfp365.sharepoint.com/sites/ti-dd/Shared%20Documents/HMDA%20Ops/HMDA/Publication%20and%20Documentation/Quarterly%20Reporting/Quarterly%20Graphing%20Tool%20Subheading%20Updates.docx?d=wcef6bcc8bc784004a5bb1110ebbead1e&csf=1&web=1&e=05gCCK)

The verbiage was sent to Jason to review, but he is OOO until Jan 2nd. If we are publishing the Q3 graphs before we receive his review, we should remove the subheadings altogether. We can add back the new ones after they are reviewed.

**Comment by audayshankar** [comment]
New verbiage (reviewed by OR)

Graph | Current Text | Proposed Updates
-- | -- | --
How has median CLTV changed? | RHS/FSA loans had the highest median CLTV while HELOCs had generally the   lowest. | Can stay the same
For   conventional conforming loans, how has median CLTV differed by   race/ethnicity? | In 2019, all racial and ethnicity groups experienced a decline in median   CLTV. | In 2022, all racial and ethnic groups experienced an increase in median CLTV   after several quarters of mostly declining CLTVs.
For   FHA loans, how has median CLTV differed by race/ethnicity? | Both Blacks and Hispanics on average had the same median CLTV for FHA   loans. | Blacks and Hispanics had similar median CLTVs for FHA loans. Whites   experienced a significant decline in median CLTV since Q2 of 2021
How have median credit scores changed? | HELOC loans had the highest median credit scores while FHA loans had the   lowest. | Conventional Non-Conforming loans had the highest median credit scores while   FHA loans had the lowest.
For   conventional conforming loans, how have median credit scores differed by   race/ethnicity? | In 2019, median credit scores increased for all racial and ethnic   groups. | After falling each quarter since 2021, median credit scores were unchanged or   slightly increasing for all racial and ethnic groups in Q3 of 2022
For   FHA loans, how have median credit scores differed by race/ethnicity? | In 2019, median credit scores increased for all groups and, in 2020, median   credit scores declined for all groups. | After falling during 2021 and Q1 2022, median credit scores were generally   unchanged or increasing for all racial and ethnic groups during Q2 and Q3 of   2022.
How have median DTI changed? | Conventional non-confirming loans on average had the lowest median DTI. | Median DTIs have generally risen for all loan types since 2021. FHA loans   have the highest median DTI.
For   conventional conforming loans, how has median DTI differed by   race/ethnicity? | For conventional conforming loans, Hispanics has the highest media DTI while   whites had the lowest. | For conventional conforming loans, Hispanics had the highest median DTI while   Whites had the lowest.
For   FHA loans, how has median DTI differed by race/ethnicity? | For FHA loans, whites had the lowest median DTI while the position of other   racial and ethnic groups changed. | For FHA loans, whites had the lowest median DTI. All racial and ethnic groups   experienced an increase in DTI since late 2021.
How have denial rates changed? | HELOC loans had the highest denial rate. | HELOCs had a significantly higher denial rate percentage compared to the   other loan types.
For   conventional conforming loans, how have denial rates differed by   race/ethnicity? | All racial and ethnic groups experienced an overall decrease in denial   rates. | Blacks and Hispanics had higher denial rates for every quarter. In 2022,   denial rates for Blacks and Hispanics increased while rates for Whites and   Asians fell.
For   FHA loans, how have denial rates differed by race/ethnicity? | Both Blacks and Hispanics on average had the same median CLTV for FHA   loans | Blacks had higher denial rates for each quarter.  Since 2021, Hispanics   showed the lowest denial rates.
How have median interest rates changed? | Median interest rates decreased overall for all loan types. | After being generally flat in 2021, median interest rates increased for all   loan types in 2022.
For   conventional conforming loans, how have median interest rates differed by   race/ethnicity? | Since 2019, all median interest rates have decreased. | After being generally flat in 2021, median interest rates increased for all   racial and ethnic groups in 2022.
For   FHA loans, how have median interest rates differed by race/ethnicity? | Interest rates decreased from 2018 quarter four to 2020. | After being generally flat in 2021, median interest rates increased for all   racial and ethnic groups in 2022.
How has the number of applications changed? | Conventional conforming applications dramatically increased since 2019. FHA   loans temporarily moved higher in 2020 Q3. | The volume of conventional conforming applications declined significantly   since the start of 2021. All other loan types declined slightly or remained   relatively consistent.
How   much of the total loan/application count do quarterly filers account   for? | How does the number of loans and application submitted from quarterly filers   compare to the total amount? | Quarterly filers account for over half of the application volume during 2021.   Annual data for 2022 has not been collected yet.
How   has the number of loans changed? | Conventional conforming loans increased starting in 2019 and the increase   quickened in 2020. VA loans have also been steadily increasing since   2019. | Conventional conforming loans experienced a significant decrease since 2021.   VA and FHA loans experienced a steadier decline.
How have median total loan costs changed? | Median total loan costs increased from 2018 to 2020 except for VA   loans. | Since Q3 2021, all median total loan costs increased, most notably VA &   FHA loans.
For   conventional conforming loans, how have median total loan costs differed by   race/ethnicity? | Since 2019, all median interest rates have decreased. | Since 2021 Q3, median total loan costs have increased for each racial and   ethnic group.
For   FHA loans, how have median total loan costs differed by race/ethnicity? | Median total loan costs increased from the start of 2018 to 2020. | Median total loan costs for all racial and ethnic groups increased from the   start of 2021.



</body>

</html>

**Comment by meissadia** [comment]
- Would we need to update the language for the GRAPH_SUMMARY since the 55 quarterly filers reflect the *previous* year, not the *current year*? https://github.com/cfpb/hmda-platform/blob/master/kubernetes/hmda-quarterly-data-service/templates/quarterly-verbiage-configmap.yaml#L6
  <img width="771" alt="Screen Shot 2023-01-11 at 12 44 58 PM" src="https://user-images.githubusercontent.com/2592907/211903053-e8aeafea-42ba-4c72-b6bd-ccfde783c884.png">
