### ISSUE TITLE
Do we really want Q022 to work as described?

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#469]
While thinking through future uses of `ValidationContext` (see https://github.com/cfpb/hmda-platform/pull/452#issuecomment-236234651), a `filingDate` or `filingPeriod` jumped out as a pretty obvious usecase.

This led me to [Q022](https://github.com/cfpb/hmda-platform/issues/182), which reads: 

>Date application received should =activity year or (activity year minus 1 or activity year minus 2).

I also checked out the code ([`Q022.scala`](https://github.com/cfpb/hmda-platform/blob/master/validation/src/main/scala/hmda/validation/rules/lar/quality/Q022.scala#L16)), and it seems to be doing just that.

However, do we _really_ want it to work this way?  I assume it is written this way because the current system has to accept filings for up to 2 years in the past.  However, _our_ system probably shouldn't work that way.  All submissions will always be for a given filing period, so the check should really be that the LAR's application date's falls within that filing period.

In addition, I believe we're **not** accepting resubmissions for _past_ filing periods (prior to 2017).  Those will be handled by the existing system, yes?  If we receive LARs for pre-2017 applications, that should indicate a **problem**, like _hey, you're submitting this to the wrong system!_.

Thoughts?

**Comment by lesgou** [comment]
@Debbie did some initial research and the two year lookback period is currently used to catch construction loans where properties are typically built within two years. 

The current system is not able to accept lars across filing years, which is why this edit is looking at the date application received data field.  Applications could be started in a previous year, which is why how you determine which loans to file in which year is based on the action taken date. Filers are currently only able to file lars for specific years only, which is why there is a des released (x2) each year.

Hope this helps.

**Comment by hkeeler** [comment]
Interesting.  OK, wasn't expecting that.  Sounds like this has to stay as-is.  I feel like this edit isn't super useful, as its really just going to check if the date isn't _waaay_ off, but I guess that's OK.  Just means [S270](https://github.com/cfpb/hmda-platform/issues/131) is doing the _real_ validation.

I am going to put these details into a comment on [`Q022.scala`](https://github.com/cfpb/hmda-platform/blob/master/validation/src/main/scala/hmda/validation/rules/lar/quality/Q022.scala#L16), and then I'll close this out.

Thanks @lesgou!

**Comment by hkeeler** [comment]
Added a comment (https://github.com/cfpb/hmda-platform/pull/452/commits/c5074d0d0e7e8c968806ea788c53cc1b53c89df5) about this in PR https://github.com/cfpb/hmda-platform/pull/452.  Closing this out.
