### ISSUE TITLE
How should we handle optional edits?

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#471]
As mentioned on #452, certain edits cannot be applied under certain circumstances.  For example, we want to allow anonymous LAR validations, and thus, all edits that compare LAR data to the institution data of the filer, cannot be applied.

Our first attempt on #452 was to filter out these edits in validation engines when the optional data (`Institution`) was not present.  However, we moved that logic to within the edit itself, always returning `Success()` when the optional data is not present.  This made testing much easier, but does give the false sense that a given edit _passed_ when it was really _ignored_.  It also means we'd be duplicating this logic within each edit that follows this pattern.

I'm curious to get other's thoughts on this.  There are currently only 5 edits with this optional institution .  I'm not sure if there are other types edits that need to be made optionalized.  That may drive whether or not this should be institution-specific, or something more general.

**Comment by hkeeler** [comment]
@lgdean put together the following as a possible solution:

* https://github.com/hkeeler/hmda-platform/compare/inst-model...lgdean:no-institution-from-hkeeler

**Comment by lgdean** [comment]
I pushed that idea farther [here](https://github.com/hkeeler/hmda-platform/compare/inst-model...lgdean:further-s025-changes).  Not totally polished: for example, it's weird that in `S025` the companion object comes before the class.  (And that `EmptyEditCheck` is there at all: it and the bulk of `inContext` would likely move somewhere more general, to serve other edits.)  Still, it shows the important parts of how the code could look, and how `S025` (and the like) would fit in with other `EditCheck`s in the Engines.

**Comment by lgdean** [comment]
The ideas from the above branches (and the commits from #477, rebased) ended up in PR #494.  I tried to keep the code open to various possibilities for answering this question.  In particular, `EmptyEditCheck` is a class, not an object, and we could easily make its `name` a constructor parameter, if needed.

Meanwhile, each edit's companion object, such as `S025`, has an `inContext` method that calls out to shared code that decides whether to instantiate the actual edit (or use `EmptyEditCheck`).  This indirection means that the knowledge of the fact of institution-dependence lives in each edit, but the logic isn't duplicated.  It also worked well for addressing @schbetsy's [question about constructor visibility](https://github.com/cfpb/hmda-platform/pull/477#issuecomment-238927684).

Right now that shared-logic place is called `IfInstitutionPresentIn.apply`, but if there are multiple ways that edits can be optional, then the object can be renamed, and the functions can have meaningful names instead. (Or whatever makes sense when the time comes, but that's my current reasoning.)

**Comment by jmarin** [comment]
@hkeeler @lgdean can this be closed?

**Comment by lgdean** [comment]
@jmarin good question. The only other info I expect to have passed in to edits (likely via the `ValidationContext`) are the activity year (Q022, [S100](https://github.com/cfpb/hmda-platform/issues/96), [S270](https://github.com/cfpb/hmda-platform/issues/131)) and the "timestamp"([S013](https://github.com/cfpb/hmda-platform/issues/97)).

At the moment, the code for PR #567 makes it look like the year will be optional, in which case, we'll need to decide what happens when there's no year. That could be part of #563 or of this ticket. Same question for the timestamp.

Also, #254 lists a different set of outside information, including prior year data, which I haven't considered here.

Even apart from all that, there's a business requirements question: @hkeeler asked whether we have the concept of an _ignored_ edit, as a possible result, and I don't feel qualified to answer that question.
