### ISSUE TITLE
DAT Parser should strip leading zeroes from parsed fields

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#475]
DAT Parser (Transmittal Sheet and LAR) should strip leading zeroes from any fields that have them, so it can accept files according to the file spec. See [this comment thread](https://github.com/cfpb/hmda-platform/pull/470#discussion_r73147076) for context. 

Here's a list of all fields that are marked as having leading zeroes in the FFIEC (DAT) [File Spec](http://www.ffiec.gov/hmda/pdf/spec2016.pdf). Ensure the parser handles all of these correctly. Investigate whether this is necessary for numeric fields (Loan Amount, Applicant Income), or whether `toInt` handles this automatically.

Transmittal Sheet:
- [ ] Respondent ID

LAR:
- [ ] Respondent ID
- [ ] Loan Amount
- [x] ~~State Code~~
- [x] ~~County Code~~
- [ ] Applicant Income

Make sure to update any specs that are affected by the change, for instance `LarDatParserSpec` and `TsDatParserSpec`.

**Comment by jmarin** [comment]
At least for some of of these, I feel this is incorrect. [FIPS codes](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standard_state_code) for state and counties, for instance, have leading zeroes, and the meaning of the code is lost if these are stripped out. A state code of `"06"' (California) is correct, and the zero should not be stripped. If we strip zeroes from state and county, codes like `16` are impossible to interpret. Is it 01006?. State 16? State 1, county 006?. Given the hierarchical nature of Census FIPS codes, they should remain as text. 

I tend to agree with this regarding numeric amounts. Loan amount is numeric so this should work for that field. The reason income is coded as text is because it can have "NA" as a reported value.

**Comment by schbetsy** [comment]
That makes sense. I'll edit the issue text to reflect that we shouldn't change how census codes are parsed.

**Comment by debseidner** [comment]
From the files institutions sent us to test, it looks like FIs will strip the leading zeros themselves from the Respondent ID since those leading zeros only existed in HMDA previously (i.e. NIC does not have Respondent ID with leading zeros) and our file spec does not say to include them. Previous year's HMDA data will have the zeros. Just an FYI that we will have to take that into account when comparing previous year's HMDA data in the edits.
