### ISSUE TITLE
Investigate deprecated  plugin used for embedded postgres testing

### ISSUE THREAD

**Issue by PatrickGoRaft** [cfpb/hmda-platform#4843]
The platform is currently using  for embedded postgres unit testing of some platform services. Due to this blocking our GItHub Action rollout it would be best to implement an alternative solution for embedded postgres in our unit tests. 

- [x] Write report on which plugins are deprecated/versions to update to

**Comment by jaredb96** [comment]
Report on deprecated Plugins:
HMDA Plugin Version Report 

06/11/2024

| Plugin                         | Version          | Deprecated/Should Be Updated?                |
|--------------------------------|------------------|----------------------------------------------|
| Logback                        | 1.2.1            | Yes, supported version 1.5x                  |
| Scala Test                     | 3.0.8            | No                                           |
| Scala Check                    | 1.17.0           | No                                           |
| Akka                           | 2.8.5            | No                                           |
| Akka Http                      | 10.5.6           | No                                           |
| Akka Http JSON                 | 1.39.2           | No                                           |
| Akka Cluster Management        | 1.40.1           | No                                           |
| Akka Cors                      | 1.2.0            | No                                           |
| Akka Kafka                     | 2.0.2            | No                                           |
| Circe                          | 0.14.5           | No                                           |
| Akka Cassandra Persistence     | 1.1.1            | Yes - our system throws errors for Cassandra |
| Slick                          | 3.4.1            | No                                           |
| Slick Postgres                 | 0.21.1           | No                                           |
| Slick Postgres                 | 0.21.1           | No                                           |
| Postgres JDBC                  | 46.2.0           | No                                           |
| H2                             | 2.2.214          | No                                           |
| Embedded Postgres (Flapdoodle) | 46.2.0           | Yes -> deprecated since 2018                 |
| Keycloak                       | 22.0.1           | No                                           |
| RestEasy                       | 6.2.4.Final      | No                                           |
| Jboss Logging                  | 3.5.1.Final      | No                                           |
| Http Components                | 4.5.14           | No                                           |
| Alpakka                        | 2.0.2            | No                                           |
| Alpakka S3                     | 2.0.1            | No                                           |
| Embedded Kafka                 | 3.7.0            | No                                           |
| Akka Quartz Scheduler          | 1.9.3-akka-2.6.x | No                                           |
| Enumeratum                     | 1.7.2            | No                                           |
| Enumeratum Circe               | 1.7.2            | No                 g                         |
| Monix                          | 3.4.1            | No                                           |
| Lettuce                        | 6.2.4.RELEASE    | No                                           |
| Java 8 Compat                  | 1.0.2            | No                                           |
| Scala Mock                     | 4.3.0            | Yes, outdated version                        |
| Guava                          | 33.0.0-jre       | No                                           |
| AWS Ses SDK                    | 1.12.484         | Yes, very old service                        |
| Cormorant                      | 0.3.0            | Yes for CVE issue                            |
