### ISSUE TITLE
populate Institution parents

### ISSUE THREAD

**Issue by lgdean** [cfpb/hmda-platform#490]
This was originally part of #438, but is pulled out into another issue because:
- it isn't needed for the edits after all (as a boolean `hasParent` suffices),
- it was likely to cause additional merge conflicts with some concurrent work (#472), and
- the process/UI that will need it isn't fully specified yet.

That said, a `Set[Institution]` will likely end up being appropriate, unless non-filing institutions look more different from filers than we expect.

**Comment by Kibrael** [comment]
Providing parent information back to a filer will be useful when a non-depository filer's agency code does not match the agency code generated by panel. The agency code for non-depositories frequently relies on the presence of a parent and several attributes of a parent in order to determine institution type which then determines agency code. 

Providing parent information gives the filer the opportunity to provide us information about why there is mismatch between our information and theirs regarding agency code and respondent ID.

**Comment by debseidner** [comment]
I got this from one of the Reg attorneys for a HMDA Help inquiry response and thought this would be helpful:

Your agency code depends on whether or not you are affiliated with a parent depository institution, i.e., whether or not your institution is a mortgage subsidiary of a depository institution.  If your institution is a mortgage subsidiary, then your agency code is the same as the agency code for your parent. If you are a nondepository institution that is not affiliated with a depository institution, then your agency code is 7.
