### ISSUE TITLE
Institution id modeled as Int

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#526]
Currently [Institution](https://github.com/cfpb/hmda-platform/blob/master/model/src/main/scala/hmda/model/institution/Institution.scala#L7) has its id modeled as an `Integer`. In 2018 we are adopting [LEI](https://en.wikipedia.org/wiki/Legal_Entity_Identifier), which is certainly alphanumeric. If we use LEI as an institution identifier in the future our model would have to be changed to have id as a String

**Comment by schbetsy** [comment]
@jmarin @hkeeler Is this as simple as updating the type of the `id` from `Int`/`Integer` to `String` and making all of the cascading changes from that? If so, I could take this issue.

But if there's deeper knowledge of the institution model required (e.g. if we want the institution id to be its own type, rather than a string), I should probably leave it for @hkeeler or @lgdean .

**Comment by jmarin** [comment]
As far as I know a `String` would suffice for now

**Comment by schbetsy** [comment]
I made a draft (accidentally-- I only intended to see how hard this change would be to make 😄 ). Is this what you're looking for? #559

**Comment by hkeeler** [comment]
Agreed, I think with what we know about `Institution.id` at this point (which is not much), keeping it a simple `String` makes sense.  And I think #559 looks about right. :)  I'll re-assign to you @schbetsy.
