### ISSUE TITLE
Update SubmissionProtocol to return SubmissionStatus code and message

### ISSUE THREAD

**Issue by nickgrippin** [cfpb/hmda-platform#599]

**Comment by awolfe76** [comment]
Just wanted to make sure I understood here. This will make the `/institutions/<institution>/filings/<period>` endpoint (and maybe others) return

```json
"id": 1,
"status": {
    "code": 1,
    "message": "created"
  }
```

instead of

```json
{
   "id": 1,
   "submissionStatus": "created"
 }
```

Right?

**Comment by awolfe76** [comment]
_Just adding this here because it seems related. If we need a separate issue let me know._

I ran the docker-compose setup and the `POST` to `/institutions/<institution>/filings/<period>/submissions` is failing. The error I see on the front-end is `TypeError: Cannot read property 'code' of undefined(…)`. This seems like it will be, at least partially (may require front-end updates too), fixed by this issue.

The response I'm seeing from `/institutions/<institution>/filings/<period>/submissions` is:
```json
{
    "id": {
        "institutionId":"0",
        "period":"2016",
        "sequenceNumber":1
    },
    "submissionStatus":"created"
}
```

[API.md](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md) shows that the response should be:
```json
{
    "id": 4,
    "submissionStatus": "created"
}
```

I think, in the end, we'll have:
```json
{
    "id": {
        "institutionId":"0",
        "period":"2016",
        "sequenceNumber":1
    },
    "status": {
        "code": 1,
        "message": "created"
    }
}
```

Would we still need `"sequenceNumber":`? `sequenceNumber` and `status.code` seem to represent the same thing. Maybe we could move the `status` object into the `id`?

**Comment by jmarin** [comment]
`sequenceNumber` is the id (sequential) for the submission (1 to N), while `status.code` is a static identifier for the particular status of that submission (1 to 12). In this particular case they are the same, but that is just a coincidence when the first submission has the status `Created`

**Comment by awolfe76** [comment]
Oh yeah, sorry got those mixed up in my head. Thanks.

So then it looks like 
```json
{
    "id": {
        "institutionId":"0",
        "period":"2016",
        "sequenceNumber":1
    },
    "status": {
        "code": 1,
        "message": "created"
    }
}
``` 
is what we want.
