### ISSUE TITLE
Parser error handling

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#62]
Provide a sensible mechanism to report parsing errors

**Comment by schbetsy** [comment]
Combining with #64, since they're basically duplicates. Text: 

"As mentioned on [#63 (comment)](https://github.com/cfpb/hmda-platform/pull/63#discussion_r53020374), we need to make sure individual invalid data fields cannot blow up the whole parser. The exact design of this is TBD."

Text of linked comment from Hans:

(on `LarCsvParser`) "The rest of this section is duplicate from the first LarCsvParser. I think this should be split up, with the first step simply being to translate a row into a common data structure (perhaps just an array of strings?), and then parse each element into the domain objects."
