### ISSUE TITLE
Implement FI Data DAT parser test

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#75]
https://github.com/cfpb/hmda-platform/blob/master/parser/shared/src/test/scala/hmda/parser/fi/FIDataDatParserSpec.scala

**Comment by schbetsy** [comment]
Since `FIData` class doesn't have a `toDAT` method, I'm not sure how to test this. Usually, I would use the same strategy as the other parser tests (convert to DAT, then parse that DAT and make sure the result matches the starting object), but that won't work here. 

Should we add a `toDAT` method to `FIData`, or use a different testing strategy?

cc @jmarin

**Comment by jmarin** [comment]
I think we don't have a `toDAT` method in `FIData` because I totally forgot to add it :)
So yes, that testing strategy should work. Keep in mind (or rather, ignore for now) that this method might generate a huge string for large datasets
