### ISSUE TITLE
Compose is broken building from master

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#763]
Steps to repro, assuming other images are up to date:
1. Build the api docker image from latest:
```
  git pull &&\
  docker-compose rm -f --all api &&\
  docker rmi hmdaplatform_api &&\
  sbt clean assembly &&\
  docker-compose up
```

2. Attempt to access the API at `192.168.99.100:4443` (possibly subbing the IP for whatever your docker host is)

3. Encounter an ERR_CONNECTION_REFUSED

This was first introduced to master in 5605c6f, the result of https://github.com/cfpb/hmda-platform/pull/751

**Comment by schbetsy** [comment]
Welp. I reproduced it locally. What is `192.168.99.100:4443`?

**Comment by hkeeler** [comment]
That's the auth-proxy.  https://github.com/cfpb/hmda-platform/blob/master/docker-compose.yml#L77.

I'm pretty sure the issue is that https://github.com/cfpb/hmda-platform/pull/756 was merged, but it was dependent on https://github.com/cfpb/hmda-platform-auth/pull/45, which was not merged.

If you revert this change locally, it _should_ fix it, but I have not yet confirmed locally:

* https://github.com/cfpb/hmda-platform/pull/756/files#diff-4e5e90c6228fd48698d074241c2ba760L77

**Comment by wpears** [comment]
Hans is right, nice catch (I'd recommend sorting by recently updated over newest if you're using github to sleuth through project changes). Once https://github.com/cfpb/hmda-platform-auth/pull/45 is merged this will be resolved; closing here.
