### ISSUE TITLE
Add institutions search endpoint

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#778]

**Comment by jmarin** [comment]
@hkeeler can you edit the description with requirements for this API endpoint? Thanks

**Comment by hkeeler** [comment]
@awolfe76, thanks for taking a first crack at this.  First off, I agree, the resource itself is probably as simple as `/institutions?domain=<domain>`.  We should probably make that parameter required so we don't return a giant list of all institutions.


As for the response, here's what the current mock service returns:

```json
    {
      "id": "1", 
      "name": "Bank 1", 
      "regulator": "FDIC",
      "domain": [
        "bank1.com",
        "bankone.com"
      ]
    }
```

It obviously doesn't have the additional IDs...those are currently hardcoded.

I think we should keep this response small, only including the bits that won't change from one filing period to the next.  Take the proposed `onPanel` flag for example.  What if a user registers their account before we'd generated the panel for the year?  They'd see the previous years panel results...or perhaps not results at all.  What if we tell an institution to refile for a past filing period?  The `onPanel` results would be for the current filing period.  I think all of this could lead to confusion.

Similarly, regulator can change from one filing period to the next, and I believe @Kibrael mentioned showing regulator may cause more confusion than any value it may provide.

I propose something like:

```json
    {
      "id": "1",
      "name": "Bank 1",
      "domains": [
        "bank1.com",
        "bankone.com"
      ],
      "externalIds": [
        {
          "name": "RSSD ID",
          "value": "12345678"
        },
        {
          "name": "EIN",
          "value": "12-3456789"
        }
      ]
    }
```

Now the **BIG** question of _what **is** our institution ID?_  We've discussed this a few times, but we've never come to a conclusion.  We can't use `respondentId`, though, since it is not stable from one filing period to the next.  Seems like for now this could just be the `id` column from the `institutions` table in the query database.  What that value is and how exactly it gets populated can figured out at another time.

If we're not OK with that approach, and we feel like we do need to solve the ID problem now, I'm happy to dive deeper into various options around this as well.

**Comment by jmarin** [comment]
Done in #798
