### ISSUE TITLE
Check that the filing institution's ARID matches the HMDA File

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform#895]
Verify that the institution (not user) that is submitting HMDA data is the same institution listed in the HMDA file. 

The identifier to use is the "agency code" and "respondent ID", which is found in the file as the transmittal sheet and the LAR.

Per conversations with team, should be implemented like an edit.
ID: S000
Language: The reported Agency Code and Respondent ID must match the Agency Code and Respondent ID for the financial institution for which you are filing. Please confirm the information below and update your file accordingly:
1) The correct file was uploaded
2) The Agency Code and Respondent ID were reported correctly in the file.

Things that we may need to update:
- [ ] meta data field #724 
- [ ] others?

**Comment by schbetsy** [comment]
This looks similar to https://github.com/cfpb/hmda-platform/issues/94. How is this one different? I want to make sure to get the logic correct when I put it into code.

**Comment by schbetsy** [comment]
Adding more info on our implementation of `S025`, for reference.

The tests for S025 say that it: (these lines are taken directly from the test suite)
- succeeds when TS's agency code and respondent ID match the Institution's
- fails when TS's agency code and respondent ID do NOT match the Institution's
- succeeds when LAR's agency code and respondent ID match the Institution's
- fails when LAR's agency code and respondent ID do NOT match the Institution's

**Comment by lesgou** [comment]
It is similar to #94 except that this matches to the institution that is filing as per selected on the institutions page in platform, and not panel.

**Comment by schbetsy** [comment]
Ohhh, interesting. In that case, I think that our version of S025 is mis-implemented. Our S025 does exactly what you've described in this ticket. It doesn't do exactly what #94 says. (It's not fully hooked up to run yet, but that's a separate issue that I'm creating a ticket for.)

Since we have an edit that does that, do we still need the edit described in #94? If so, I could move our current S025 implementation to be called S000, and we could re-open #94 to be reimplemented.

**Comment by lesgou** [comment]
Closing since this is implemented through #94
