### ISSUE TITLE
Validation (2017): S011 (Record Identifier)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#92]
**Edit #:** S011
**Type:** Syntactical
**Category:** Transmittal Sheet (TS) & Loan/Application Register (LAR)
**Column:** Record Identifier

The HMDA file must contain at least one loan/application record (record identifier = 2).

Additional resources:
- [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
- [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
- [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by kgudel** [comment]
Requires knowledge of the whole file.

**Comment by jmarin** [comment]
The edit itself has been implemented [here](https://github.com/cfpb/hmda-platform/blob/master/validation/src/main/scala/hmda/validation/rules/lar/syntactical/S011.scala)

**Comment by hkeeler** [comment]
Can this one be closed?  Sounds like its done.

**Comment by lesgou** [comment]
@jmarin following up. Can this be closed?

**Comment by schbetsy** [comment]
This can't be closed yet, since the edit isn't fully implemented. S011 and S040 have to be run differently from the rest of the edits, and they aren't hooked up yet.

Marking as unblocked, since we now have ability to analyze the entire file.

@jmarin Should they get an Akka Streams implementation like the Macro edits? Or something else?
