### ISSUE TITLE
Validation (2017): S100 (Activity Year)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#96]
**Edit #:** S100
**Type:** Syntactical
**Category:** Transmittal Sheet (only)
**Column:** Activity Year

Activity year must = year being processed (= 2017).

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by kgudel** [comment]
How do we want to tell the edit what year the activity year should be? This links with #131.

**Comment by jmarin** [comment]
I personally believe this edit doesn't make much sense given how the architecture for `hmda-platform` has been designed

**Comment by schbetsy** [comment]
I was under the impression that all of the edits we are writing are specific to the 2017 filing year (since the file format will change drastically in 2018, and therefore the parser, model, and edits will change drastically with it). If that were true, it wouldn't be a problem to hard-code 2017 into the edit.

Is this not the case? How much of the system will we try to re-use in 2018?

**Comment by jmarin** [comment]
We should try to reuse as much as possible. There will be some changes in data model / parser, etc. but many of the edits will most likely be the same (though this is still pending, and no decision has been made as of yet).

**Comment by schbetsy** [comment]
Fair. I'm glad we'll try to re-use.

In any case, this edit still seems valuable. If a FI tries to submit 2016 data to the 2017 system, we'd want to stop them. Why do you say this edit doesn't make sense?
