### ISSUE TITLE
Create Sample Files

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform#978]
Create two sample files with test data 1) transmittal sheets 2) lars

**Comment by jmarin** [comment]
Encrypted???

**Comment by lesgou** [comment]
Removing encryption requirement.

**Comment by kgudel** [comment]
Just a couple questions about the requirement for these files.

1. Should these two files be the result of taking one full submission file and splitting it so that the first line (transmittal sheet) is in one file and the rest (lars) are in a second file?
2. Should we use one of our test files for this, or should it have real data? 
3. How long should the file be? 
4. Should it be clear of edits? 
5. What format should they be in, just our regular pipe delimited?
6. Where should the final files go?

**Comment by lesgou** [comment]
I can answer a few of the questions, and will then need @jonathan to fill in the rest.

- [ ] 1. I would recommend that each of the two files contain data from multiple test files.  This means, the TS should have multiple rows, and the LARs should have data from more than one sample file.


- [ ] 2. Test files please  


- [ ] 5. They should be in the pipe delimited format.

**Comment by feomike** [comment]
[] 3. Length isn't too significant for testing purposes.  I would say in the low 10,000s and a non round number so when our testers import the files they can have an line number to count and test
[] 4. It would be a good idea to be clear of syntax and validity edits
[] 6. These files are not required to be part of HMDA Platform, but I can see why they could be of value if we need to repeat the process.   I can give you the internal person to whom they should be delivered.

**Comment by jonathan** [comment]
the @jonathan is not the Jonathan you are looking for

**Comment by jflugel** [comment]
I received the files and forwarded them to our point of contact for testing.

**Comment by jflugel** [comment]
@ericspry Hi Eric. Can you grant me access to close this ticket? Thank you.

**Comment by jflugel** [comment]
Closing ticket. File received and submitted to data team.
