### ISSUE TITLE
Validation (2017): S028 (Timestamp)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#98]
**Edit #:** S028
**Type:** Syntactical
**Category:** Transmittal Sheet (only)
**Column:** Timestamp

Timestamp must be numeric and in ccyymmddhhmm format.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by lgdean** [comment]
In order for this edit to work as specified, we'd need to update the parser to return a string for this field. (Per #257). @jmarin (and anyone else), do you see a problem with that plan?

**Comment by jmarin** [comment]
I see where you are coming from, but I think this change has negative consequences. In a type safe domain model like the one we are building, the [`TransmittalSheet`](https://github.com/cfpb/hmda-platform/blob/master/model/src/main/scala/hmda/model/fi/ts/TransmittalSheet.scala) has the `timestamp` field which is coded as `Long` (as it should be, per the "Data Type" field in the File Spec). If the parser generates a String, we have a type mismatch between the File Spec and our model implementation, which I think is a step backwards. This might also be problematic from a backwards compatibility point of view (legacy data stores that field as numeric as well). 

The first part of this edit (numeric) is already checked for by the act of parsing the file due to type constraints. The format is checked in S028. So yes, a bit of this edit is redundant with out data model since a parseable file can't fail the numeric condition.

**Comment by schbetsy** [comment]
So if the timestamp field is non-numeric in the submitted file, what happens from the user's perspective?

**Comment by jmarin** [comment]
I think they should get an error stating that the file is malformed because of that reason. The parser doesn't do that yet

**Comment by lgdean** [comment]
Business requirement question:
1. Does that error need to mention S028?

Process questions:
2. Is the relevant work, then, already captured as part of #62 (and/or #64)?

3. If the answer to question 1 is yes, then do we have (or do we need) a place to keep track of specific Syntactic edits whose failure messages need to come from the parser?

**Comment by debseidner** [comment]
I think that if you mention S028 when the user is trying to upload the file and it won't parse, this might confuse the user - like why is this edit happening here but every other edit happens later in the process? Although, I agree that it makes sense up there (all the syntactical ones should really). It might make sense to just use a generic statement that we cannot read that field in the file because it is not numeric.

**Comment by schbetsy** [comment]
I think this can be closed. From the team's discussions, it seems that it's not important to show specific EditCheck messages when a user submits a malformed (unparseable) file. Showing sensible error messages for parse errors is part of #62.
